### ISSUE TITLE
Update for 3.0+

### ISSUE THREAD

**Issue by wyhinton** [K-410/textension#4]
Looks like this no longer works with blender 3.0+.

Installing gives error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Primary User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\textension-master\__init__.py", line 686, in <module>
    class TEXTENSION_OT_cut_internal(utils.TextOperator):
AttributeError: module 'textension-master.utils' has no attribute 'TextOperator'
```

If the project is dead it might be a good thing to note as much on the readme.

**Comment by Hydrocallis** [comment]
The version check function seems to be misbehaving.

The blender version number has been lowered, try modifying 82 to 0.

https://github.com/K-410/textension/blob/72bafe3b75c51839b63a1218032e61b6ab5ae22f/utils.py#L9



```

def bpy_version_check():
    if bpy.app.version[1] < 0:
        raise Exception("\nMinimum Blender version 2.82 required\n")
        
```

**Comment by Hydrocallis** [comment]
This is what separates the IF minutes between version 3 and version 2.

```
    if bpy.app.version[0] == 2:
        if bpy.app.version[1] < 82:
            raise Exception("\nMinimum Blender version 2.82 required\n")

    elif bpy.app.version[0] == 3:
        if bpy.app.version[1] < 0:
            raise Exception("\nMinimum Blender version 2.82 required\n")
                
```
